### ISSUE TITLE
Sukijan asennus epäonnistuu

### ISSUE THREAD

**Issue by ottopoika** [ahomansikka/sukija#1]
"make sukija" epäonnistuu seuraavalla virheilmoituksella (corevoikko/master):

cp vocabulary/erikoisalat/linux-distributions.lex sukija/voikonsanat/erikoisalat/linux-distributions.lex
cp vocabulary/erikoiset.lex sukija/voikonsanat/erikoiset.lex
cp vocabulary/erikoissanat.lex sukija/voikonsanat/erikoissanat.lex
cp vocabulary/lainen.lex sukija/voikonsanat/lainen.lex
cp vocabulary/lukusanat.lex sukija/voikonsanat/lukusanat.lex
cp vocabulary/poikkeavat.lex sukija/voikonsanat/poikkeavat.lex
cp vocabulary/seikkasanat.lex sukija/voikonsanat/seikkasanat.lex
cp vocabulary/suhdesanat.lex sukija/voikonsanat/suhdesanat.lex
cp vocabulary/taivutustaydennykset.lex sukija/voikonsanat/taivutustaydennykset.lex
cp vocabulary/yhdyssanat.lex sukija/voikonsanat/yhdyssanat.lex
python sukija/generate_lex.py
######################################
#Malaga class not found for (hyljätä, hyljätä)
#Malaga class not found for (hylätä, hylätä)
#Malaga class not found for (joutsi, peitsi)
#Malaga class not found for (jälki, jälki)
#Malaga class not found for (levätä, levätä)
#Malaga class not found for (peitsi, peitsi)
Compiling "suomi.sym".
Compiling "suomi.all".
Compiling "suomi.lex".
mallex: Unknown symbol "kielto". ("erikoissanat.lex", line 33, column 84)
malmake: Compilation failed.

**Comment by ottopoika** [comment]
Sain tuon läpi checkouttaamalla tags/rel-suomimalaga-1.17, mutta nyt "mvn package" epäonistuu 

Tests in error: 
  testSuggestion(peltomaa.sukija.voikko.SuggestionTest): Can't load library: /home/ottopoika/vvfst/lib/libvoikko.so

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] sukija ............................................ SUCCESS [0.436s]
[INFO] sukija-core ....................................... SUCCESS [7.716s]
[INFO] sukija-malaga ..................................... SUCCESS [1.236s]
[INFO] sukija-voikko ..................................... FAILURE [0.493s]
[INFO] sukija-ui ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] --------------------------------------------------------------

**Comment by ahomansikka** [comment]
Sukijassa oli paljon bugeja. Nyt "make sukija" pitäisi onnistua.
Ilmoitukset "Malaga class not found" voi jättää huomiota (mutta sanat,
joille ei ole taivutusluokkaa, jäävät tunnistamatta).

Jos käytät vfst-morfologiaa, libvoikon pitää olla käännetty hakemistoon
$HOME/vvfst ja sanaston pitää olla hakemistossa $HOME/vvfst/voikkodict
Jotenkin näin

Hakemistossa corevoikko/suomimalaga:
make vvfst
make vvfst-install DESTDIR=~/vvfst/voikkodict

Tai (jos haluat tunnistaa vanhoja kirjoitusasuja (esim. symbooli) ja
yleisiä kirjoitusvirheita (esim. kirjoittaa)):
make vvfst-sukija; make vvfst-sukija-install DESTDIR=~/vvfst/voikkodict/


Hakemistossa corevoiko (tarvitsee mm. paketit autoconf ja libtool):
./autogen.sh
./configure --enable-vfst --prefix=/$HOME/vvfst \
   --with-dictionary-path=$HOME/vvfst/voikkodict
make
make install

**Comment by ahomansikka** [comment]
Toimiiko? Jos toimii, suljen tämäm tiketin.

**Comment by ottopoika** [comment]
Hei, en pääse nyt testaamaan. Jos haluat sulkea tiketin niin ok. Avaan uuden jos tarvetta.
