### ISSUE TITLE
sukija-voikko build fails

### ISSUE THREAD

**Issue by marta-lapina** [ahomansikka/sukija#2]
Since there are no releases tagged or CI in this repo, it's hard to tell if I'm doing something wrong or the build for this commit of sukija is broken: https://github.com/ahomansikka/sukija/commit/86c570dd7c92e24db2b4917af91a954a189ca839

I'm trying to build sukija-voikko but it fails: 

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running peltomaa.sukija.voikko.SuggestionTest
[main] INFO peltomaa.sukija.voikko.VoikkoMorphology - Initializing VoikkoMorphology.
[main] INFO peltomaa.sukija.voikko.VoikkoMorphology - Voikko vfst morphology.
Syöte wanhoille, tulos [vanhoille], odotettu tulos [vanha].
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.963 sec <<< FAILURE!
testSuggestion(peltomaa.sukija.voikko.SuggestionTest)  Time elapsed: 0.725 sec  <<< FAILURE!
junit.framework.AssertionFailedError
        at junit.framework.Assert.fail(Assert.java:55)
        at junit.framework.Assert.assertTrue(Assert.java:22)
        at junit.framework.Assert.assertTrue(Assert.java:31)
        at junit.framework.TestCase.assertTrue(TestCase.java:201)
        at peltomaa.sukija.voikko.SuggestionTest.testSuggestion(SuggestionTest.java:66)

The same test passes for sukija-malaga.

**Comment by ahomansikka** [comment]
You are probably using Voikko version that does not give base forms.
Try
$ echo alusta | voikkospell -m|grep BASEFORM

Result should be

A(alusta):1:BASEFORM=alusta
A(alusta):2:BASEFORM=alustaa
A(alusta):3:BASEFORM=alku
A(alusta):4:BASEFORM=alunen
A(alusta):5:BASEFORM=alus

**Comment by marta-lapina** [comment]
I tried with the "voikkospell" that I have and the output was empty.
How do I get the right voikko?

**Comment by ahomansikka** [comment]
git clone https://github.com/voikko/corevoikko.git

**Comment by ahomansikka** [comment]
Compile libvoikko like this
./autogen.sh
./configure --enable-vfst --prefix=/$HOME/vvfst --with-dictionary-path=$HOME/vvfst/voikkodict
make
make install

--prefix and -with-dictionary-path can be different

**Comment by marta-lapina** [comment]
That's strange - I had done this before (found the instructions in sukija.properties) but repeated just to be sure.

Installed libvoikko still doesn't show the baseforms. It shows other stuff, though:
C: alusta
A(alusta):1:CLASS=nimisana
A(alusta):1:NUMBER=singular
A(alusta):1:SIJAMUOTO=nimento
A(alusta):1:STRUCTURE==pppppp
A(alusta):2:CLASS=teonsana
A(alusta):2:MOOD=imperative
A(alusta):2:NEGATIVE=both
A(alusta):2:NUMBER=singular
A(alusta):2:PERSON=2
A(alusta):2:STRUCTURE==pppppp
A(alusta):3:CLASS=nimisana
A(alusta):3:NUMBER=singular
A(alusta):3:SIJAMUOTO=sisaeronto
A(alusta):3:STRUCTURE==pppppp
A(alusta):4:CLASS=nimisana
A(alusta):4:NUMBER=singular
A(alusta):4:SIJAMUOTO=osanto
A(alusta):4:STRUCTURE==pppppp

**Comment by marta-lapina** [comment]
This part of "make" is supposed to happen or is this a problem?

copying selected object files to avoid basename conflicts...
libtool: link: ln setup/interface.o .libs/libvoikko.lax/lt1-interface.o || cp setup/interface.o .libs/libvoikko.lax/lt1-interface.o
ln: creating hard link `.libs/libvoikko.lax/lt1-interface.o' => `setup/interface.o': Operation not permitted
libtool: link: ln hyphenator/interface.o .libs/libvoikko.lax/lt2-interface.o || cp hyphenator/interface.o .libs/libvoikko.lax/lt2-interface.o
ln: creating hard link `.libs/libvoikko.lax/lt2-interface.o' => `hyphenator/interface.o': Operation not permitted
[and so on]

**Comment by ahomansikka** [comment]
Do you have 2 versions of Voikko in your machine? I get different results.

$ echo alusta | voikkospell -m
C: alusta
A(alusta):1:BASEFORM=alusta
A(alusta):1:CLASS=nimisana
A(alusta):1:NUMBER=singular
A(alusta):1:SIJAMUOTO=nimento
A(alusta):1:STRUCTURE==pppppp
A(alusta):1:WORDBASES=+alusta(alusta)
A(alusta):2:BASEFORM=alustaa
A(alusta):2:CLASS=teonsana
A(alusta):2:MOOD=imperative
A(alusta):2:NEGATIVE=both
A(alusta):2:NUMBER=singular
A(alusta):2:PERSON=2
A(alusta):2:STRUCTURE==pppppp
A(alusta):2:TENSE=present_simple
A(alusta):2:WORDBASES=+alustaa(alustaa)
A(alusta):3:BASEFORM=alku
A(alusta):3:CLASS=nimisana
A(alusta):3:NUMBER=singular
A(alusta):3:SIJAMUOTO=sisaeronto
A(alusta):3:STRUCTURE==pppppp
A(alusta):3:WORDBASES=+alku(alku)
A(alusta):4:BASEFORM=alunen
A(alusta):4:CLASS=nimisana
A(alusta):4:NUMBER=singular
A(alusta):4:SIJAMUOTO=osanto
A(alusta):4:STRUCTURE==pppppp
A(alusta):4:WORDBASES=+alunen(alunen)
A(alusta):5:BASEFORM=alus
A(alusta):5:CLASS=nimisana
A(alusta):5:NUMBER=singular
A(alusta):5:SIJAMUOTO=osanto
A(alusta):5:STRUCTURE==pppppp
A(alusta):5:WORDBASES=+alus(alus)

**Comment by ahomansikka** [comment]
>This part of "make" is supposed to happen or is this a problem?

I don't think that should happen. Perhaps you should send a message about that to Libvoikko mailing list.

**Comment by marta-lapina** [comment]
I think I will. Btw, on what OS you built yours?

**Comment by ahomansikka** [comment]
I have Ubuntu 14.04 LTS.

BTW my libvoikko and voikkospell is version 3.7.1.

**Comment by ahomansikka** [comment]
Since this seems to be a problem with Voikko, I close this.

**Comment by marta-lapina** [comment]
Can you, please, send me full instructions how you compiled and installed voikko? I tried on a clean virtual machine and still the same problem. I think I'm missing some steps. :(

**Comment by ahomansikka** [comment]
Perhaps you are missing autogen.sh?

./autogen.sh
./configure --enable-vfst --prefix=/$HOME/vvfst --with-dictionary-path=$HOME/vvfst/voikkodict
make
make install

**Comment by marta-lapina** [comment]
No, that I am doing. What dictionaries do you have inside $HOME/vvfst/voikkodict? And how do you get them? I got mine by installing suomimalaga

**Comment by ahomansikka** [comment]
If your error is 
"copying selected object files to avoid basename conflicts...
libtool: link: ln setup/interface.o .libs/libvoikko.lax/lt1-interface.o || cp setup/interface.o .libs/libvoikko.lax/lt1-interface.o
ln: creating hard link .libs/libvoikko.lax/lt1-interface.o' =>setup/interface.o': Operation not permitted
libtool: link: ln hyphenator/interface.o .libs/libvoikko.lax/lt2-interface.o || cp hyphenator/interface.o .libs/libvoikko.lax/lt2-interface.o
ln: creating hard link .libs/libvoikko.lax/lt2-interface.o' =>hyphenator/interface.o': Operation not permitted
[and so on]"

the error is in compilation of libvoikko, I think, and not in vocabulary.
I make my vocabulary like this

cd suomimalaga
make vvfst-sukija; make vvfst-sukija-install DESTDIR=~/vvfst/voikkodict/

see file suomimalaga/vvfst/generate_sukija.py

**Comment by marta-lapina** [comment]
I'll try and build the vocabulary this way, it might help.

"make vvfst-sukija" gave error:
foma -f vvfst/main-sukija.foma | grep -v "defined but not used" 2>&1
/bin/sh: foma: command not found

do you know what is that "foma"?

**Comment by ahomansikka** [comment]
Foma is the compiler that makes the dictionary from lexc files. 
http://foma.googlecode.com/

**Comment by marta-lapina** [comment]
Making dictionaries in a new way changed the analysis results, but I didn't get the base forms yet.

[vagrant@localhost suomimalaga]$ echo alusta | voikkospell -m
C: alusta
A(alusta):1:CLASS=teonsana
A(alusta):1:FSTOUTPUT=[Lt][Xp]alustaa[X]alusta[Tk][Ap][P2][Ny][Eb]
A(alusta):1:MOOD=imperative
A(alusta):1:NEGATIVE=both
A(alusta):1:NUMBER=singular
A(alusta):1:PERSON=2
A(alusta):1:STRUCTURE==pppppp
A(alusta):1:TENSE=present_simple
A(alusta):2:CLASS=nimisana
A(alusta):2:FSTOUTPUT=[Ln][Xp]alus[X]alu[Sp][Ny]sta
A(alusta):2:NUMBER=singular
A(alusta):2:SIJAMUOTO=osanto
A(alusta):2:STRUCTURE==pppppp
A(alusta):3:CLASS=nimisana
A(alusta):3:FSTOUTPUT=[Ln][Xp]alunen[X]alu[Sp][Ny]sta
A(alusta):3:NUMBER=singular
A(alusta):3:SIJAMUOTO=osanto
A(alusta):3:STRUCTURE==pppppp
A(alusta):4:CLASS=nimisana
A(alusta):4:FSTOUTPUT=[Ln][Xp]alusta[X]alust[Sn][Ny]a
A(alusta):4:NUMBER=singular
A(alusta):4:SIJAMUOTO=nimento
A(alusta):4:STRUCTURE==pppppp
A(alusta):5:CLASS=nimisana
A(alusta):5:FSTOUTPUT=[Ln][Xp]alku[X]alu[Sela][Ny]sta
A(alusta):5:NUMBER=singular
A(alusta):5:SIJAMUOTO=sisaeronto
A(alusta):5:STRUCTURE==pppppp
[vagrant@localhost suomimalaga]$

**Comment by ahomansikka** [comment]
Do you have 2 different vocabularies? I get this

echo alusta|~/vvfst/bin/voikkospell -m
C: alusta
A(alusta):1:BASEFORM=alusta
A(alusta):1:CLASS=nimisana
A(alusta):1:NUMBER=singular
A(alusta):1:SIJAMUOTO=nimento
A(alusta):1:STRUCTURE==pppppp
A(alusta):1:WORDBASES=+alusta(alusta)
A(alusta):2:BASEFORM=alustaa
A(alusta):2:CLASS=teonsana
A(alusta):2:MOOD=imperative
A(alusta):2:NEGATIVE=both
A(alusta):2:NUMBER=singular
A(alusta):2:PERSON=2
A(alusta):2:STRUCTURE==pppppp
A(alusta):2:TENSE=present_simple
A(alusta):2:WORDBASES=+alustaa(alustaa)
A(alusta):3:BASEFORM=alku
A(alusta):3:CLASS=nimisana
A(alusta):3:NUMBER=singular
A(alusta):3:SIJAMUOTO=sisaeronto
A(alusta):3:STRUCTURE==pppppp
A(alusta):3:WORDBASES=+alku(alku)
A(alusta):4:BASEFORM=alunen
A(alusta):4:CLASS=nimisana
A(alusta):4:NUMBER=singular
A(alusta):4:SIJAMUOTO=osanto
A(alusta):4:STRUCTURE==pppppp
A(alusta):4:WORDBASES=+alunen(alunen)
A(alusta):5:BASEFORM=alus
A(alusta):5:CLASS=nimisana
A(alusta):5:NUMBER=singular
A(alusta):5:SIJAMUOTO=osanto
A(alusta):5:STRUCTURE==pppppp
A(alusta):5:WORDBASES=+alus(alus)


My dictionaries are like this

$ ls -R ~/vvfst/voikkodict
~/vvfst/voikkodict:
5/

~/vvfst/voikkodict/5:
mor-standard/

~/vvfst/voikkodict/5/mor-standard:
autocorr.vfst  index.txt  mor.vfst

$ cat ~/vvfst/voikkodict/5/mor-standard/index.txt 
Voikko-Dictionary-Format: 5
Language: fi-x-standard
Copyright: 2006-2014 Hannu Väisänen, Harri Pitkänen, Teemu Likonen and others
License: GPL version 2 or later
Description: suomi (perussanasto)
SM-Version: 1.18
SM-Patchinfo: 
Build-Config: GENLEX_OPTS=--style=dialect,foreign,foreignloan,inappropriate,incorrect,international,old --min-frequency=10 --extra-usage=education,human,it,medicine,nature,orgname,science --sukija EXTRA_LEX=
Build-Date: Fri, 04 Sep 2015 07:36:02 +0000
Morphology-Backend: finnishVfst

**Comment by marta-lapina** [comment]
Why is your dictionary format 5? I only get 2.

**Comment by marta-lapina** [comment]
[vagrant@localhost libvoikko]$ cat ~/vvfst/voikkodict/2/mor-standard/voikko-fi_FI.pro
info: Voikko-Dictionary-Format: 2

info: Language-Code: fi_FI
info: Copyright: 2006-2012 Hannu Väisänen, Harri Pitkänen, Teemu Likonen and others
info: License: GPL version 2 or later
info: Language-Variant: standard
info: Description: suomi (perussanasto)
info: SM-Version: 1.15
info: SM-Patchinfo:
info: Build-Config: GENLEX_OPTS=--style=dialect,foreign,foreignloan,inappropriate,incorrect,international,old --min-frequency=10 --extra-usage=it,medicine,science,education,orgname --sukija EXTRA_LEX=
info: Build-Date: Fri, 04 Sep 2015 09:12:10 +0000
info: Morphology-Backend: vfst
[vagrant@localhost libvoikko]$

**Comment by ahomansikka** [comment]
You have old version of the dictionary (Voikko-Dictionary-Format: 2). It should be 5.

**Comment by marta-lapina** [comment]
how can I get the new one?

**Comment by ahomansikka** [comment]
From GitHub

git clone https://github.com/voikko/corevoikko.git

**Comment by marta-lapina** [comment]
I checked out (rel-libvoikko-3.7.1) tag and it gave me a format 2 dictionary.

**Comment by ahomansikka** [comment]
How did you make the dictionary?
This should give you version 5:

cd suomimalaga
make vvfst-sukija; make vvfst-sukija-install DESTDIR=~/vvfst/voikkodict/

**Comment by marta-lapina** [comment]
The dictionary itself is format 5, but it gets installed in a folder '2'.

[vagrant@localhost suomimalaga]$ ls -la ~/vvfst/voikkodict/2
total 12
drwxr-xr-x 3 vagrant vagrant 4096 Sep  4 12:15 .
drwxr-xr-x 3 vagrant vagrant 4096 Sep  4 12:15 ..
drwxr-xr-x 2 vagrant vagrant 4096 Sep  4 14:37 mor-standard


[vagrant@localhost suomimalaga]$ cat ~/vvfst/voikkodict/2/mor-standard/index.txt
Voikko-Dictionary-Format: 5
Language: fi-x-standard
Copyright: 2006-2014 Hannu Väisänen, Harri Pitkänen, Teemu Likonen and others
License: GPL version 2 or later
Description: suomi (perussanasto)
SM-Version: 1.17
SM-Patchinfo:
Build-Config: GENLEX_OPTS=--style=dialect,foreign,foreignloan,inappropriate,incorrect,international,old --min-frequency=10 --extra-usage=it,medicine,science,education,orgname --sukija EXTRA_LEX=
Build-Date: Fri, 04 Sep 2015 11:15:15 +0000
Morphology-Backend: vfst
[vagrant@localhost suomimalaga]$

**Comment by marta-lapina** [comment]
I didn't remove the old dictionary folder before installing the new. I guess that's the problem.

**Comment by ahomansikka** [comment]
Perhaps. Delete everyting from ~/vvfst and start again.

**Comment by ahomansikka** [comment]
Or from ~/vvfst/voikkodict only.

**Comment by marta-lapina** [comment]
Hmm unfortunately, not. This is what I get:
[vagrant@localhost suomimalaga]$ ls -la ~/vvfst/voikkodict/2/mor-standard/
total 4700
drwxr-xr-x 2 vagrant vagrant    4096 Sep  4 14:56 .
drwxr-xr-x 3 vagrant vagrant    4096 Sep  4 14:56 ..
-rw-r--r-- 1 vagrant vagrant     495 Sep  4 14:56 index.txt
-rw-r--r-- 1 vagrant vagrant 4797120 Sep  4 14:56 mor.vfst

But index.txt says it's format 5..

**Comment by ahomansikka** [comment]
What are the last lines of suomimalaga/Makefile? They shoud be

vvfst-sukija-install: vvfst-sukija
        install -m 755 -d $(DESTDIR)/5/mor-$(VOIKKO_VARIANT)
        install -m 644 $(VVFST_BINDIST) $(DESTDIR)/5/mor-$(VOIKKO_VARIANT)

Can you just rename the directory?
mv ~/vvfst/voikkodict/2 ~/vvfst/voikkodict/5

**Comment by marta-lapina** [comment]
those are:
vvfst-sukija-install: vvfst-sukija
	install -m 755 -d $(DESTDIR)/2/mor-$(VOIKKO_VARIANT)
	install -m 644 $(VVFST_BINDIST) $(DESTDIR)/2/mor-$(VOIKKO_VARIANT)

**Comment by ahomansikka** [comment]
When I do
git clone https://github.com/voikko/corevoikko.git

I get
vvfst-sukija-install: vvfst-sukija
        install -m 755 -d $(DESTDIR)/5/mor-$(VOIKKO_VARIANT)
        install -m 644 $(VVFST_BINDIST) $(DESTDIR)/5/mor-$(VOIKKO_VARIANT)

Do you do 'git clone' into empty directory?

**Comment by marta-lapina** [comment]
When I clone https://github.com/voikko/corevoikko.git and compile the dictionaries, I get a format 5 dictionary.
That is accepted by libvoikko version 3.7.1, right?

**Comment by marta-lapina** [comment]
Finally :) I compiled the dictionary from latest commit and libvoikko from this commit: https://github.com/voikko/corevoikko/commit/b807a3275ccfe95b625780ab54467d4b941fcad8
And baseform recognition works. 
Thanks for help!

**Comment by ahomansikka** [comment]
If you use dictionary from https://github.com/voikko/corevoikko.git and if libvoikko version 3.7.1 does not accept it, you can compile libvoikko from that clone.

**Comment by mthierydydu** [comment]
Tested at changeset `ae975dd` with 2.2 dictionaries from http://puimula.org/htp/testing/voikko-snapshot/:

I was also missing the base forms: using the **morpho** dictionary when instanciating `Voikko` worked for me: `new Voikko("fi-x-morpho", ...)`.

No need to compile a dictionary.
