### ISSUE TITLE
Some XML parsing errors

### ISSUE THREAD

**Issue by marta-lapina** [ahomansikka/sukija#5]
Hello,

I'm running sukija and it stops when it's trying to parse some file, not sure which one. I thought you could help me understand where I did something wrong.

The commit I'm working with: 86c570dd7c92e24db2b4917af91a954a189ca839

What was the error:

2155 [coreLoadExecutor-5-thread-1] ERROR peltomaa.sukija.suggestion.SuggestionParser  – a org.xml.sax.SAXParseException Content is not allowed in prolog.
2155 [coreLoadExecutor-5-thread-1] ERROR peltomaa.sukija.suggestion.SuggestionParser  – b org.xml.sax.SAXParseException Content is not allowed in prolog.

Where I think it comes from:

https://github.com/ahomansikka/sukija/blob/86c570dd7c92e24db2b4917af91a954a189ca839/sukija-core/src/main/java/peltomaa/sukija/suggestion/SuggestionParser.java#L53

Additional notes:

- I have suggestions.txt in my solr home, not suggestions.xml.
- I haven't changed sukija.properties file before building sukija.

Is this error related to suggestions file? Should it be some specific format or removed altogether?

P.S. If you prefer to receive questions about support to a specific mailing list rather than have new issues raised, just let me know how to reach you. :)

**Comment by ahomansikka** [comment]
If you have uncommented the line
#sukija.suggestionFile = suggestions.xml
in sukija.properties it is trying to parse file
suggestions.xml. The format of that file is defined in file
src/main/xsd/SuggestionInput.xsd

What is in your file suggestions.txt?

**Comment by marta-lapina** [comment]
here, contents of suggestions.txt:

Char             "w" "v"               # Esim. wanha => vanha.
CharCombination  "bdgkptwšž"      "ptkgbdvsz"
Length3                                # Esim. kauttta => kautta.
Regex            "^([0-9]+)"    ""     # Poista numerot sanan alusta.
Regex            "(\"-|''-|--)" "-"    # Esim. linja"-auto => linja-auto.
Apostrophe                             # Esim. Bordeaux'iin => Bordeauxiin Bordeaux.

Regex "V(h)V"   "hd"   # Puhistus => puhdistus.
Regex "VV(v)V"  "d"    # Pöyvän => pöydän, uuven => uuden.

Regex "r(t)elle"        "r"
Regex "h(t)elle"        "d"
Regex "V(t)elle"        "d"

Regex "(n)pi(?:A|in)?$"  "m"    # Pienenpi, pienenpiä, pienenpiin.

Regex  "(illi)(?:nen|s)" "i"    # Traagillinen => traaginen.
Regex  "C[ae](hi)C"      "i"    # Aina(h)inen, ete(h)inen.
Regex  "(?:uu|yy)(e)"    "de"   # Uuen => uuden.
Regex  "ai(j)[eou]"      ""     # Ai(j)emmin, ai(j)omme, kai(j)utin.

Regex  "V(mm)Ai[ns]"     "m"    # Alammainen => alamainen.
Regex  "V(m)Ai[ns]"      "mm"   # Lähimäinen => lähimmäinen.


#  private static final String[] end = {
#    "ki", "n",  // Puuki => puukin. Ei ole sijapääte.
#    "ks", "i",  // Puuks(i); myös yks(i), kaks(i).
#    "ll", "a",  // Puull(a).
#    "ll", "e",  // Puull(e)
#    "ll", "ä",  // Pääll(ä).
#    "ss", "a",  // Puuss(a).
#    "ss", "ä",  // Pääss(ä).
#    "st", "a",  // Puust(a).
#    "st", "ä",  // Pääst(ä).
#    "tt", "a",  // Puutt(a).
#    "tt", "ä",  // Päätt(ä).

# Vartia => vartija.
#
Regex  "..C(ia)(?=ni|si|nsa|mme|tte|n$|a|ta|na|ks[ie]|ssa|sta|h?an|lla|lta|lle|tta|t$|in)" "ija"
Regex  "..C(ioi)(?=den|tten|na|ks[ie]|ssa|sta|hin|lla|lta|lle|tta|ine)"                    "ijoi"
Regex  "..C(iä)(?=ni|si|nsä|mme|tte|n$|ä|tä|nä|ks[ie]|ssä|stä|h?än|llä|ltä|lle|ttä|t$|in)" "ijä"
Regex  "..C(iöi)(?=den|tten|nä|ks[ie]|ssä|stä|hin|llä|ltä|lle|ttä|ine)"                    "ijöi"


Regex      "..C[aouyäö](i)(?=nen|se|st[aeä]|sn[aä]|si)" ""  # Hevoinen => hevonen.

Regex  "..C[aouyäö](n)(?=en)"            "in"   # Punanen => punainen.
Regex  "..C[aouyäö](s)(?=e|t[aeä]|nA|i)" "is"

**Comment by ahomansikka** [comment]
You have old text format, now suggestions file must be in xml format. 
See file conf/suggestions.xml

**Comment by marta-lapina** [comment]
Thanks, I'll try it! Should I add my txt contents to conf/suggestions.xml? Where do they go in conf/suggestions.xml structure?

**Comment by ahomansikka** [comment]
11.12.2015, 12:08, marta-lapina kirjoitti:
> Thanks, I'll try it! Should I add my txt contents to conf/suggestions.xml? Where do they go in conf/suggestions.xml structure?


Regex goes to <regex>

Apostrophe => <apostrophe/

Char => <char>

CharCombination => <char>

Length3 => <regex> =>
<input>(\p{L})\1{2,} $1$1</input>      

But you can not just copy them. Syntax is different. See file 
conf/suggestions.xml

And if you can read Finnish, see file ohje.pdf (-:

**Comment by marta-lapina** [comment]
Just to clarify the situation - I haven't uncommented the line
#sukija.suggestionFile = suggestions.xml

The file format still should be XML in that case?

**Comment by ahomansikka** [comment]
11.12.2015, 14:45, marta-lapina kirjoitti:
> Just to clarify the situation - I haven't uncommented the line
> #sukija.suggestionFile = suggestions.xml

You have found a bug!

If that line is uncommentend, the file suggestions.xml should not be read.

I'll look at it on the weekend.

**Comment by marta-lapina** [comment]
Oh! Good to know. :)

**Comment by marta-lapina** [comment]
Meanwhile I'll try to provide the suggestions file from conf/suggestions.xml as a workaround for this bug.
Sadly, I don't speak Finnish, so can't read the guide. Where should files from conf/ go? Into solr home /opt/solr/server/solr or into each solr core's 'conf' folder?

**Comment by ahomansikka** [comment]
If you do not want to use suggestions and if your schema.xml file has something like

suggestionFile = "suggestions.txt"

remove it and restart Solr. That should fix the problem.


>Where should files from conf/ go? Into solr home /opt/solr/server/solr or into each solr core's 'conf' folder

Right. If you have the newest version of Sukija

make asenna

puts the config files into <solr-source>/server/solr/sukija
or /var/solr/data/sukija depending on how you have configured Sukija. See file sukija.properties and 2
choices for "sukija.sukija" and "sukija.jetty".


May I ask, if you do not know Finnish, why are you using Sukija? I thought that Sukija can be used only to index Finnish texts.
 
________________________________________
L�hett�j�: marta-lapina [notifications@github.com]
L�hetetty: 11. joulukuuta 2015 16:58
Vastaanottaja: ahomansikka/sukija
Kopio: Hannu V�is�nen
Aihe: Re: [sukija] Some XML parsing errors (#5)

Meanwhile I'll try to provide the suggestions file from conf/suggestions.xml as a workaround for this bug.
Sadly, I don't speak Finnish, so can't read the guide. Where should files from conf/ go? Into solr home /opt/solr/server/solr or into each solr core's 'conf' folder?

�

**Comment by marta-lapina** [comment]
Thanks, I changed schema.xml and the error is gone. 

I'm working in a team that's part Finnish and we work with Finnish texts. :)

**Comment by ahomansikka** [comment]
14.12.2015, 13:33, marta-lapina kirjoitti:
> Thanks, I changed schema.xml and the error is gone.

Fine!

> I'm working in a team that's part Finnish and we work with Finnish texts.:)

Thanks for the info.

By the way, I just updated Sukija in GitHub. I added VoikkoTokenizer 
that uses function tokens() from Voikko.java.

**Comment by marta-lapina** [comment]
The bug is fixed then? We'll stick to workaround because it's easier for us, we are using a specific version (commit) of sukija with our Solr. Still, great to hear that it's OK now!

**Comment by ahomansikka** [comment]
14.12.2015, 16:32, marta-lapina kirjoitti:
> The bug is fixed then?

I was wrong. There was no bug. The error was "synonyms.txt" etc in your 
schema file.

**Comment by marta-lapina** [comment]
Allright. :) Thanks for help!
