### ISSUE TITLE
Sukija fails to install

### ISSUE THREAD

**Issue by yatzy** [ahomansikka/sukija#6]
Hey,

With my Ubuntu 16.04 maven fails to install regardless that Voikko and Solr are placed to the right places mentioned at the installation document. The error I get:

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building sukija 2.1.1
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.puimula.voikko:libvoikko:jar:3.7 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.557 s
[INFO] Finished at: 2016-05-06T15:00:36+03:00
[INFO] Final Memory: 13M/212M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sukija: Could not resolve dependencies for project peltomaa.sukija:sukija:jar:2.1.1: Failure to find org.puimula.voikko:libvoikko:jar:3.7 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by ahomansikka** [comment]
Löytyykö tiedosto
~/.m2/repository/org/puimula/voikko/libvoikko/3.7/libvoikko-3.7.jar
?

**Comment by yatzy** [comment]
Tiedostot hakemistossa: libvoikko-3.7.jar.lastUpdated  libvoikko-3.7.pom.lastUpdated

**Comment by ahomansikka** [comment]
06.05.2016, 15:10, Juha Lehtiranta kirjoitti:
> Tiedostot hakemistossa: libvoikko-3.7.jar.lastUpdated  libvoikko-3.7.pom.lastUpdated

Jotain on mennyt pieleen, koska siellä pitäisi olla
libvoikko-3.7.jar  libvoikko-3.7.pom

**Comment by yatzy** [comment]
Poistin maven-kansion ja yritin uudestaaan -> sama virhe ..

**Comment by ahomansikka** [comment]
Mene hakemistoon corevoikko/libvoikko/java ja tee

mvn install

enne kuin rupeat asentamaan Sukijaa.

Tarvitset my�s libvoikon C++-koodin k��nnettyn�.

________________________________________
L�hett�j�: Juha Lehtiranta [notifications@github.com]
L�hetetty: 6. toukokuuta 2016 15:17
Vastaanottaja: ahomansikka/sukija
Kopio: Hannu V�is�nen; Comment
Aihe: Re: [ahomansikka/sukija] Sukija fails to install (#6)

Poistin maven-kansion ja yritin uudestaaan -> sama virhe ..

�

**Comment by yatzy** [comment]
libvoikon output ja mainutut surefire-raportit https://www.dropbox.com/sh/usn4bnzpr6fjamy/AADR5iKsabLeQkhSjUP33MIwa?dl=0 :

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.726 s
[INFO] Finished at: 2016-05-07T13:54:51+03:00
[INFO] Final Memory: 18M/283M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project libvoikko: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/yatzy/Lataukset/corevoikko/libvoikko/java/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by yatzy** [comment]
Ei käänny: 

Results :

Tests in error: 
  VoikkoTest.anotherObjectCanBeCreatedUsedAndDeletedInParallel:76 » Voikko Speci...
  VoikkoTest.initWithCorrectDictWorks:133 » Voikko Specified dictionary variant ...
  VoikkoJnaLatinTest>VoikkoTest.anotherObjectCanBeCreatedUsedAndDeletedInParallel:76 » Voikko
  VoikkoJnaLatinTest>VoikkoTest.initWithCorrectDictWorks:133 » Voikko Specified ...

Tests run: 100, Failures: 0, Errors: 4, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.726 s
[INFO] Finished at: 2016-05-07T13:54:51+03:00
[INFO] Final Memory: 18M/283M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project libvoikko: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/yatzy/Lataukset/corevoikko/libvoikko/java/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

[org.puimula.libvoikko.VoikkoJnaLatinTest.txt](https://github.com/ahomansikka/sukija/files/253380/org.puimula.libvoikko.VoikkoJnaLatinTest.txt)
[org.puimula.libvoikko.VoikkoTest.txt](https://github.com/ahomansikka/sukija/files/253381/org.puimula.libvoikko.VoikkoTest.txt)

**Comment by ahomansikka** [comment]
En osaa auttaa Voikon enk� sen Java-palikan k��nt�misess�, koska en ole tehnyt kumpaakaan.
Asiasta pit�� kysy� Voikon postituslistalta.

http://voikko.puimula.org/mail.html


Toimisiko libvoikom versio 4.0.1?
http://mvnrepository.com/artifact/org.puimula.voikko/libvoikko/4.0.1

________________________________________
L�hett�j�: Juha Lehtiranta [notifications@github.com]
L�hetetty: 7. toukokuuta 2016 13:59
Vastaanottaja: ahomansikka/sukija
Kopio: Hannu V�is�nen; Comment
Aihe: Re: [ahomansikka/sukija] Sukija fails to install (#6)

Ei k��nny:

Results :

Tests in error:
VoikkoTest.anotherObjectCanBeCreatedUsedAndDeletedInParallel:76 � Voikko Speci...
VoikkoTest.initWithCorrectDictWorks:133 � Voikko Specified dictionary variant ...
VoikkoJnaLatinTest>VoikkoTest.anotherObjectCanBeCreatedUsedAndDeletedInParallel:76 � Voikko
VoikkoJnaLatinTest>VoikkoTest.initWithCorrectDictWorks:133 � Voikko Specified ...

Tests run: 100, Failures: 0, Errors: 4, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.726 s
[INFO] Finished at: 2016-05-07T13:54:51+03:00
[INFO] Final Memory: 18M/283M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project libvoikko: There are test failures.
[ERROR]
[ERROR] Please refer to /home/yatzy/Lataukset/corevoikko/libvoikko/java/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

org.puimula.libvoikko.VoikkoJnaLatinTest.txt<https://github.com/ahomansikka/sukija/files/253380/org.puimula.libvoikko.VoikkoJnaLatinTest.txt>
org.puimula.libvoikko.VoikkoTest.txt<https://github.com/ahomansikka/sukija/files/253381/org.puimula.libvoikko.VoikkoTest.txt>

�

**Comment by ahomansikka** [comment]
Jos virhe tulee vasta testien aikana, voi kokeilla

mvn -DskipTests=true install

________________________________________
L�hett�j�: Juha Lehtiranta [notifications@github.com]
L�hetetty: 7. toukokuuta 2016 13:59
Vastaanottaja: ahomansikka/sukija
Kopio: Hannu V�is�nen; Comment
Aihe: Re: [ahomansikka/sukija] Sukija fails to install (#6)

Ei k��nny:

Results :

Tests in error:
VoikkoTest.anotherObjectCanBeCreatedUsedAndDeletedInParallel:76 � Voikko Speci...
VoikkoTest.initWithCorrectDictWorks:133 � Voikko Specified dictionary variant ...
VoikkoJnaLatinTest>VoikkoTest.anotherObjectCanBeCreatedUsedAndDeletedInParallel:76 � Voikko
VoikkoJnaLatinTest>VoikkoTest.initWithCorrectDictWorks:133 � Voikko Specified ...

Tests run: 100, Failures: 0, Errors: 4, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.726 s
[INFO] Finished at: 2016-05-07T13:54:51+03:00
[INFO] Final Memory: 18M/283M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project libvoikko: There are test failures.
[ERROR]
[ERROR] Please refer to /home/yatzy/Lataukset/corevoikko/libvoikko/java/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

org.puimula.libvoikko.VoikkoJnaLatinTest.txt<https://github.com/ahomansikka/sukija/files/253380/org.puimula.libvoikko.VoikkoJnaLatinTest.txt>
org.puimula.libvoikko.VoikkoTest.txt<https://github.com/ahomansikka/sukija/files/253381/org.puimula.libvoikko.VoikkoTest.txt>

�

**Comment by ahomansikka** [comment]
Taitaa toimia. Suljettu.
